spring:
  application:
    name: jpastart
  datasource:
    url: jdbc:postgresql://localhost:5432/jpastart
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate.format_sql: true